### ISSUE TITLE
[Bug]: Buttons Not Working (with PwrS cmd run) 

### ISSUE THREAD

**Issue by K9Paradox** [eaaasun/CCStopper#16]
### What happened?

CCStopper.bat buttons are not functional. The PowerShell command _"set-executionpolicy remotesigned"_ was run prior to see if it would fix, unfortunately not though. If the PowerShell script is run directly in PowerShell it will close all the processes. I'm wondering it might be an issue with Windows 11 or just simply no longer works. 
**End Adobe Processes Button**: Non-functional
**Remove AGS Button**: reload the cmd window but is Non-functional
**Patch Acrobat Button**: appears to function
**Github Repo Button**: Fully functional
**Exit Button**: Fully functional 

Windows Build:  **22000.556 Windows 11 Pro.**
User Account is an administrator on the machine.
If CCStopper.bat is run as admin the cmd windows flickers very rapidly saying 'button' is not recognized.
Are there any other workarounds to having the buttons become functional or sol?

**Comment by eaaasun** [comment]
[Fixed in 1.1.3](https://github.com/eaaasun/CCStopper/releases/tag/v1.1.3). I didn't like the buttons either lol; the UI has been reverted to a keyboard-based layout. 

By the way, please let me know if everything works on Windows 11, as I have not updated to it yet. Thanks!

**Comment by K9Paradox** [comment]
Do you have a discord I could contact you on or something? Process quitting still not functional 
[https://imgur.com/a/1K8TBY2](url)
https://imgur.com/a/1K8TBY2

**Comment by K9Paradox** [comment]
Any ideas?
